services:
  # A Docker web service
  - type: web
    name: webdis
    runtime: node
    plan: free
    buildCommand: npm i
    startCommand: npm run start
    region: frankfurt

databases:
  # db 1
  - name: db
    plan: free
    region: frankfurt