services:
  # A Docker web service
  - type: web
    name: webdis
    runtime: node
    rootDir: webdis
    healthCheckPath: /
    plan: free
    buildCommand: npm i
    startCommand: npm run start

databases:
  # db 1
  - name: db
    plan: free